version: "3.7"

services:

  jaeger:
    image: jaegertracing/all-in-one:1.27
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 14250:14250 
      - 16686:16686
